language: node_js

node_js:
  - "lts/*" # Current
  - "node" # Last

addons:
    code_climate:
        repo_token: 360e6a58aa1dfbefbdd18149c6217164e822d39d8577ce99dd6f89fe5da5b28d

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - npm ci

script:
  - npm run test
  - npm run check:linter
  - npm run check:security

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT