language: node_js

node_js:
  - "lts/*" # Current
  - "node" # Last

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - npm ci

script:
  - npm run test
  - npm run check:security

after_script:
  - ./cc-test-reporter after-build -d --coverage-input-type lcov --exit-code $TRAVIS_TEST_RESULT